### ISSUE TITLE
I can't get 2.0 of the module to work

### ISSUE THREAD

**Issue by DFoxinator** [m1ga/com.miga.gifview#13]
Every time I try to load a gif with version 2.0 of the module, my app crashes. To confirm it's not my app, I made a new, bare-bones Titanium project.

It crashes with this error:
```
[ERROR] :  TiApplication: (main) [1,142] Sending event: exception on thread: main msg:android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class pl.droidsonroids.gif.GifImageView; Titanium 6.0.0,2016/11/13 01:23,undefined
[ERROR] :  TiApplication: android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class pl.droidsonroids.gif.GifImageView
[ERROR] :  TiApplication: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
[ERROR] :  TiApplication: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
[ERROR] :  TiApplication: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
[ERROR] :  TiApplication: 	at com.miga.gifview.GifViewProxy$GifView.<init>(GifViewProxy.java:236)
[ERROR] :  TiApplication: 	at com.miga.gifview.GifViewProxy.createView(GifViewProxy.java:97)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:490)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:476)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:514)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:498)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:476)
[ERROR] :  TiApplication: 	at ti.modules.titanium.ui.widget.tabgroup.TiUIAbstractTab.getContentView(TiUIAbstractTab.java:57)
[ERROR] :  TiApplication: 	at ti.modules.titanium.ui.widget.tabgroup.TiUIActionBarTab$TabFragment.onCreateView(TiUIActionBarTab.java:46)
[ERROR] :  TiApplication: 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
[ERROR] :  TiApplication: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
[ERROR] :  TiApplication: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
[ERROR] :  TiApplication: 	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
[ERROR] :  TiApplication: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
[ERROR] :  TiApplication: 	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
[ERROR] :  TiApplication: 	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
[ERROR] :  TiApplication: 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1106)
[ERROR] :  TiApplication: 	at android.support.v4.view.ViewPager.populate(ViewPager.java:952)
[ERROR] :  TiApplication: 	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1474)
[ERROR] :  TiApplication: 	at android.view.View.measure(View.java:18788)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.view.TiCompositeLayout.constrainChild(TiCompositeLayout.java:398)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.view.TiCompositeLayout.onMeasure(TiCompositeLayout.java:278)
[ERROR] :  TiApplication: 	at android.view.View.measure(View.java:18788)
[ERROR] :  TiApplication: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
[ERROR] :  TiApplication: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
[ERROR] :  TiApplication: 	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
[ERROR] :  TiApplication: 	at android.view.View.measure(View.java:18788)
[ERROR] :  TiApplication: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
[ERROR] :  TiApplication: 	at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:391)
[ERROR] :  TiApplication: 	at android.view.View.measure(View.java:18788)
[ERROR] :  TiApplication: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
[ERROR] :  TiApplication: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
[ERROR] :  TiApplication: 	at android.view.View.measure(View.java:18788)
[ERROR] :  TiApplication: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:901)
[ERROR] :  TiApplication: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
[ERROR] :  TiApplication: 	at android.view.View.measure(View.java:18788)
[ERROR] :  TiApplication: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
[ERROR] :  TiApplication: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
[ERROR] :  TiApplication: 	at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
[ERROR] :  TiApplication: 	at android.view.View.measure(View.java:18788)
[ERROR] :  TiApplication: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
[ERROR] :  TiApplication: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
[ERROR] :  TiApplication: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
[ERROR] :  TiApplication: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
[ERROR] :  TiApplication: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
[ERROR] :  TiApplication: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
[ERROR] :  TiApplication: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
```

Any help/guidance is greatly appreciated.

**Comment by DFoxinator** [comment]
@m1ga An update on this - I tried a bunch of things, and I was only able to get this scenario to work in 6.0.0: I just used on old version of this module, and I upgraded it to work with 6.0.0. This leads me to believe the problem has something to do with the new GifImageView version baked into the latest version of this module.

**Comment by m1ga** [comment]
It looks like I've mixed up my branches in the last commit :( can you try this version please:
https://github.com/m1ga/com.miga.gifview/releases/tag/2.1

**Comment by DFoxinator** [comment]
@m1ga thanks a bunch for the quick fix, it seems to work well now! I'll continue to test and let you know if I come across any other issues with the new version.
