### ISSUE TITLE
ANR exception in Google Play console. 

### ISSUE THREAD

**Issue by annakozy2011** [m1ga/com.miga.gifview#9]
I am getting a lot of these in Google Play Console. I suspect you may need to update gifimageview framework.

java.lang.ArithmeticException: divide by zero
	at com.felipecsl.gifimageview.library.GifDecoder.advance(GifDecoder.java:229)
	at com.felipecsl.gifimageview.library.GifImageView.run(GifImageView.java:157)
	at java.lang.Thread.run(Thread.java:818)

**Comment by m1ga** [comment]
I'm using the latest version and this bug was fixed in an older version: https://github.com/felipecsl/GifImageView/pull/36 but perhaps the bug still exists. I'll have a look at the weekend!

**Comment by annakozy2011** [comment]
No, i just updated, sorry I had the older version
